config/routes.rb
Calledit::Application.routes.draw do
  devise_for :users

  resources :predictions

  resources :problems
  root :to => redirect('/problems')

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
	belongs_to :problem
  attr_accessible :body, :problem_id, :username
end

app/models/problem.rb
class Problem < ActiveRecord::Base
	has_many :predictions
  attr_accessible :description, :name, :outcome
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  # GET /predictions
  # GET /predictions.json
  def index
    @predictions = Prediction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @predictions }
    end
  end

  # GET /predictions/1
  # GET /predictions/1.json
  def show
    @prediction = Prediction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prediction }
    end
  end

  # GET /predictions/new
  # GET /predictions/new.json
  def new
    @prediction = Prediction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prediction }
    end
  end

  # GET /predictions/1/edit
  def edit
    @prediction = Prediction.find(params[:id])
  end

  # POST /predictions
  # POST /predictions.json
  def create
    @prediction = Prediction.new(params[:prediction])

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to @prediction, notice: 'Prediction was successfully created.' }
        format.json { render json: @prediction, status: :created, location: @prediction }
      else
        format.html { render action: "new" }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /predictions/1
  # PUT /predictions/1.json
  def update
    @prediction = Prediction.find(params[:id])

    respond_to do |format|
      if @prediction.update_attributes(params[:prediction])
        format.html { redirect_to @prediction, notice: 'Prediction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1
  # DELETE /predictions/1.json
  def destroy
    @prediction = Prediction.find(params[:id])
    @prediction.destroy

    respond_to do |format|
      format.html { redirect_to predictions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])
    @prediction = @problem.predictions.build
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Called It!</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Called It!</a>
      <ul class="nav">
        <li class="active"><a href="/problems">Problems</a></li>
        <li ><%= link_to 'New Problem', new_problem_path %></li>
      </ul>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </div>
  </div>
</div>
<div class="container">
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>
<footer>
  <div class="container">
    Eszett2 2013
  </div>
</footer>
</body>
</html>

app/views/predictions/_form.html.erb
<%= form_for(@prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :problem_id %>
  <div class="field">
    <%= f.label :problem_id %><br />
    <%= f.number_field :problem_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/predictions/edit.html.erb
<h1>Editing prediction</h1>

<%= render 'form' %>

<%= link_to 'Show', @prediction %> |
<%= link_to 'Back', predictions_path %>

app/views/predictions/index.html.erb
<h1>Listing predictions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Body</th>
    <th>Problem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @predictions.each do |prediction| %>
  <tr>
    <td><%= prediction.username %></td>
    <td><%= prediction.body %></td>
    <td><%= prediction.problem_id %></td>
    <td><%= link_to 'Show', prediction %></td>
    <td><%= link_to 'Edit', edit_prediction_path(prediction) %></td>
    <td><%= link_to 'Destroy', prediction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prediction', new_prediction_path %>

app/views/predictions/new.html.erb
<h1>New prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', predictions_path %>

app/views/predictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @prediction.username %>
</p>

<p>
  <b>Body:</b>
  <%= @prediction.body %>
</p>

<p>
  <b>Problem:</b>
  <%= @prediction.problem_id %>
</p>


<%= link_to 'Edit', edit_prediction_path(@prediction) %> |
<%= link_to 'Back', predictions_path %>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :outcome %><br />
    <%= f.text_field :outcome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/i2ndex.html - Copy.erb
<h1>Listing problems</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Outcome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= problem.name %></td>
    <td><%= problem.description %></td>
    <td><%= problem.outcome %></td>
    <td><%= link_to 'Show', problem %></td>
    <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
    <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/index.html.erb
<h1>Listing Problems</h1>

<% @problems.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |problem| %>
      <div class="span4">

        <h4><%= link_to problem.name, problem %></h4>
        <%= problem.description %>
        <%= problem.outcome %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span9">
  </div>

  <div class="span6">
    <p><b>Name: </b><%= @problem.name %></p>
    <p><b>Description: </b> </br><%= @problem.description %></p>
    <p><b>Outcome: </b><%= @problem.outcome %></p>
    <h3>Predictions</h3>
    <% @problem.predictions.each do |prediction| %>
      <div>
        <strong><%= prediction.username %></strong>
        <br />
        <p><%= prediction.body %></p>
      </div>
    <% end %>
    <%= render 'predictions/form' %>
    <p>
      <%= link_to 'Edit', edit_problem_path(@problem) %> |
      <%= link_to 'Destroy', @problem, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', problem_path %>
    </p>
  </div>
</div>